name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps
        run: |
          pip install -e .[dev]

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests
        run: pytest -q

      - name: Install Azure CLI (for bicep build)
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Bicep build (syntax validation)
        run: az bicep build --file infra/main.bicep

      # Optional: Uncomment to run what-if against a test RG (requires AZURE_CREDENTIALS login)
      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: What-if (preview deployment)
      #   run: az deployment group what-if -g $RESOURCE_GROUP -f infra/main.bicep -p @infra/parameters.example.json
